version: '3.8'
services:
  postgres-db:
    image: postgres:16
    container_name: simple-expense-manager-db
    restart: always

    environment:
      POSTGRES_DB: expense_manager_db
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: password_dev

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
